# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(650, 471)
        MainWindow.setWindowFilePath("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.file_browser = QtWidgets.QPushButton(self.centralwidget)
        self.file_browser.setObjectName("file_browser")
        self.gridLayout_2.addWidget(self.file_browser, 0, 2, 1, 1)
        self.credentials_label = QtWidgets.QLabel(self.centralwidget)
        self.credentials_label.setObjectName("credentials_label")
        self.gridLayout_2.addWidget(self.credentials_label, 0, 0, 1, 1)
        self.folder_label = QtWidgets.QLabel(self.centralwidget)
        self.folder_label.setObjectName("folder_label")
        self.gridLayout_2.addWidget(self.folder_label, 2, 0, 1, 1)
        self.folder_id = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.folder_id.sizePolicy().hasHeightForWidth())
        self.folder_id.setSizePolicy(sizePolicy)
        self.folder_id.setMaximumSize(QtCore.QSize(16777215, 25))
        self.folder_id.setAcceptDrops(False)
        self.folder_id.setObjectName("folder_id")
        self.gridLayout_2.addWidget(self.folder_id, 2, 1, 1, 1)
        self.credentials_path = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.credentials_path.sizePolicy().hasHeightForWidth())
        self.credentials_path.setSizePolicy(sizePolicy)
        self.credentials_path.setMaximumSize(QtCore.QSize(16777215, 25))
        self.credentials_path.setAcceptDrops(False)
        self.credentials_path.setObjectName("credentials_path")
        self.gridLayout_2.addWidget(self.credentials_path, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.authorize = QtWidgets.QPushButton(self.centralwidget)
        self.authorize.setObjectName("authorize")
        self.horizontalLayout_3.addWidget(self.authorize)
        self.copy = QtWidgets.QPushButton(self.centralwidget)
        self.copy.setObjectName("copy")
        self.horizontalLayout_3.addWidget(self.copy)
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setObjectName("clear")
        self.horizontalLayout_3.addWidget(self.clear)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.authorize.clicked.connect(MainWindow.authorize_clicked)
        self.copy.clicked.connect(MainWindow.copy_clicked)
        self.clear.clicked.connect(MainWindow.clear_clicked)
        self.file_browser.clicked.connect(MainWindow.browser_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GDriveCopy"))
        self.file_browser.setText(_translate("MainWindow", "Browser"))
        self.credentials_label.setText(_translate("MainWindow", "Credentials :"))
        self.folder_label.setText(_translate("MainWindow", "Folder ID :"))
        self.authorize.setText(_translate("MainWindow", "Authorize"))
        self.copy.setText(_translate("MainWindow", "Start Copy"))
        self.clear.setText(_translate("MainWindow", "Clear"))

